name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight (UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Disables GitHub Actions default token

      - name: Set Up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream and Fetch Changes
        run: |
          git remote add upstream https://github.com/your-upstream-repo.git
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit
          git push origin main
